spring:
  application:
    name: t1-repo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: iamroot

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql