CREATE TABLE IF NOT EXISTS tasks
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255),
    description VARCHAR(255),
    user_id     bigint,
    CONSTRAINT tasks_pk PRIMARY KEY (id)
);

INSERT INTO tasks (title, description, user_id) VALUES
('Task 1', 'Description of Task 1', 1),
('Task 2', 'Description of Task 2', 2),
('Task 3', 'Description of Task 3', 1);