CREATE TABLE IF NOT EXISTS tasks
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255),
    description VARCHAR(255),
    user_id     bigint,
    CONSTRAINT tasks_pk PRIMARY KEY (id)
);

INSERT INTO tasks (title, description, user_id) VALUES
('Задача 1', 'Описание задачи 1', 1),
('Задача 2', 'Описание задачи 2', 2),
('Задача 3', 'Описание задачи 3', 1);