CREATE TABLE tasks
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT tasks_pk PRIMARY KEY,
    title       VARCHAR,
    description VARCHAR,
    user_id     bigint
)

INSERT INTO tasks (id, title, description, user_id) VALUES
('Task 1', 'Description of Task 1', 1),
('Task 2', 'Description of Task 2', 2),
('Task 3', 'Description of Task 3', 1);