CREATE TABLE IF NOT EXISTS tasks
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255),
    description VARCHAR(255),
    user_id     bigint,
    CONSTRAINT tasks_pk PRIMARY KEY (id)
);
