DROP TABLE IF EXISTS tasks;

CREATE TABLE IF NOT EXISTS tasks
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    user_id     bigint NOT NULL,
    status      VARCHAR(50) NOT NULL,
    CONSTRAINT tasks_pk PRIMARY KEY (id)
);
